### ISSUE TITLE
Consider switching to LGPL or some variant of BSD/MIT license

### ISSUE THREAD

**Issue by orospakr** [urizev/android-vector-flags#1]
Hey, my goal here is not to sound self-entitled or anything, but just want to be sure that you're aware that folks may not use your library in their non-FOSS apps under the current GPLv3 license terms (GitHub may have generated it for you when you created your project).

If that's intentional, then go ahead and close this ticket :)

(btw, I assume you processed some SVG flags into vector drawables; where did you find those and what license terms are they under?)

Cheers.

**Comment by urizev** [comment]
Library license changed. Thanks for the advise. I really didn't think about it I use the library for internal projects.

I mainly get the sources from Wikipedia ([sample](https://en.wikipedia.org/wiki/Flag_of_Canada#/media/File:Flag_of_Canada.svg)) so they are public domain. I use [this tool](http://inloop.github.io/svg2android/) for transforming the SVG. If a flag is too easy I do it manually.

As I said I use the library for internal use so it lacks many flags. If you would like to use it or contribute, you're welcome.

I have some future changes in mind but I have neither time not urgency to do it.

Thanks!!

**Comment by orospakr** [comment]
Amazing, thanks for the quick turnaround! :D

**Comment by urizev** [comment]
BTW, the library is in jitpack if you need it
